<?xml version="1.0"?>
<robot name="logical_camera_urdf" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:macro name="logical_camera_urdf" params="prefix logical_camera_parent *origin">
    <xacro:property name="length" value="0.2"/>
    <xacro:property name="width" value="0.050"/>
    <xacro:property name="height" value="0.050"/>

    <joint name="${prefix}logical_camera_joint" type="fixed">
	<xacro:insert_block name="origin" />
	<parent link="${logical_camera_parent}"/>
	<child link="${prefix}base_link"/>
    </joint>

    <!-- link list -->
    <link name="${prefix}base_link">
      <visual>
        <origin xyz="0 0 ${height / 2}" rpy="0 0 0" />
        <geometry>
          <box size="${width} ${length} ${height}" />
        </geometry>
        <material name="dark_grey">
          <color rgba="0.1 0.1 0.1 1.0"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 ${height / 2}" rpy="0 0 0" />
        <geometry>
          <box size="${width} ${length} ${height}" />
        </geometry>
        <material name="dark_grey"/>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <inertia ixx="0.1" ixy="0" ixz="0"
                 iyy="0.1" iyz="0"
                 izz="0.1" />
        <mass value="1" />
      </inertial>
    </link>

  </xacro:macro>
</robot>
