robot2_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
     - robot2_elbow_joint
     - robot2_shoulder_lift_joint
     - robot2_shoulder_pan_joint
     - robot2_wrist_1_joint
     - robot2_wrist_2_joint
     - robot2_wrist_3_joint
  gains:
      robot2_elbow_joint: {p: 50000, d: 30, i: 0.3, i_clamp: 25}
      robot2_shoulder_lift_joint: {p: 95000, d: 15.0, i: 0.0, i_clamp: 50}
      robot2_shoulder_pan_joint: {p: 35000, d: 30.0, i: 0.3, i_clamp: 1}
      robot2_wrist_1_joint: {p: 10500, d: 10, i: 0.1, i_clamp: 1}
      robot2_wrist_2_joint: {p: 150, d: 5, i: 0, i_clamp: 1}
      robot2_wrist_3_joint: {p: 250, d: 10, i: 0, i_clamp: 1}
  constraints:
      goal_time: 5.0
      stopped_velocity_tolerance: 3.0
      robot2_shoulder_pan_joint: {trajectory: &trajectory_pos_constraint 0.2, goal:  &goal_pos_constraint 0.1}
      robot2_shoulder_lift_joint: {trajectory: *trajectory_pos_constraint, goal: *goal_pos_constraint}
      robot2_elbow_joint: {trajectory: *trajectory_pos_constraint, goal: *goal_pos_constraint}
      robot2_wrist_1_joint: {trajectory: *trajectory_pos_constraint, goal: *goal_pos_constraint}
      robot2_wrist_2_joint: {trajectory: *trajectory_pos_constraint, goal: *goal_pos_constraint}
      robot2_wrist_3_joint: {trajectory: *trajectory_pos_constraint, goal: *goal_pos_constraint}
  stop_trajectory_duration: 0.5
  state_publish_rate:  50
  action_monitor_rate: 10
